application: coffeehousecode
version: 11
runtime: python
api_version: 1

handlers:
- url: /update.*
  script: tweet.py
  login: admin

- url: /static
  static_dir: static

- url: .*
  script: main.py
